github: Add test for setup-poetry caching

diff --git a/.github/workflows/test_actions.yml b/.github/workflows/test_actions.yml
--- a/.github/workflows/test_actions.yml
+++ b/.github/workflows/test_actions.yml
@@ -55,6 +55,40 @@ jobs:
           fi
         shell: bash
 
+  test_setup_poetry_caching:
+    name: Test setup-poetry caching
+    runs-on: ${{ matrix.os }}
+    needs: test_setup_poetry
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        id: setup-poetry
+        uses: ./setup-poetry
+      - name: Check that Poetry was loaded from the cache
+        if: steps.setup-poetry.outputs.cache-hit != 'true'
+        run: |
+          echo "::error title=Test Failure::The cache was not hit."
+          exit 1
+        shell: bash
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
+        run: |
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
+  
   test_check_project_version:
     name: Test check-project-version
     runs-on: ubuntu-latest
@@ -143,7 +177,7 @@ jobs:
   test_results:
     name: Test Results
     runs-on: ubuntu-latest
-    needs: [test_setup_python, test_setup_poetry, test_check_project_version, test_update_project_version]
+    needs: [test_setup_python, test_setup_poetry, test_setup_poetry_caching, test_check_project_version, test_update_project_version]
     if: ${{ !cancelled() }}
     steps:
       - run: exit 0
