github: Add a use_cache=false test

diff --git a/.github/workflows/test_actions.yml b/.github/workflows/test_actions.yml
--- a/.github/workflows/test_actions.yml
+++ b/.github/workflows/test_actions.yml
@@ -55,8 +55,8 @@ jobs:
           fi
         shell: bash
 
-  test_setup_poetry_caching:
-    name: Test setup-poetry caching
+  test_setup_poetry_cache_hit:
+    name: Test setup-poetry (cache hit)
     runs-on: ${{ matrix.os }}
     needs: test_setup_poetry
     strategy:
@@ -73,11 +73,43 @@ jobs:
       - name: Set up Poetry
         id: setup-poetry
         uses: ./setup-poetry
-      - name: Check that Poetry was loaded from the cache
+      - name: Expect cache hit 
         if: steps.setup-poetry.outputs.cache-hit != 'true'
+        run: echo "::error title=Test Failure::Expected cache hit."; exit 1
+        shell: bash
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
         run: |
-          echo "::error title=Test Failure::The cache was not hit."
-          exit 1
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
+  
+  test_setup_poetry_no_cache:
+    name: Test setup-poetry (no cache)
+    runs-on: ${{ matrix.os }}
+    needs: test_setup_poetry
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        id: setup-poetry
+        uses: ./setup-poetry
+        with:
+          use-cache: false
+      - name: Expect cache miss 
+        if: steps.setup-poetry.outputs.cache-hit == 'true'
+        run: echo "::error title=Test Failure::Expected cache miss."; exit 1
         shell: bash
       - name: Create project
         run: poetry new test-project
@@ -177,7 +209,14 @@ jobs:
   test_results:
     name: Test Results
     runs-on: ubuntu-latest
-    needs: [test_setup_python, test_setup_poetry, test_setup_poetry_caching, test_check_project_version, test_update_project_version]
+    needs: [
+      test_setup_python, 
+      test_setup_poetry, 
+      test_setup_poetry_cache_hit,
+      test_setup_poetry_no_cache,
+      test_check_project_version,
+      test_update_project_version
+    ]
     if: ${{ !cancelled() }}
     steps:
       - run: exit 0
