github: Add tests for setup-python and setup-poetry

diff --git a/.github/workflows/test_actions.yml b/.github/workflows/test_actions.yml
--- a/.github/workflows/test_actions.yml
+++ b/.github/workflows/test_actions.yml
@@ -5,6 +5,54 @@ on:
   workflow_dispatch:
 
 jobs:
+  test_setup_python:
+    name: Test setup-python
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Check Python version
+        run: |
+          import sys
+          version = sys.version_info[:2]
+          expected_version = tuple("${{ matrix.python-version }}".split("."))
+          if version != expected_version:
+              print(f"::error title=Test Failure::The Python version does not match. Got {version}, expected {expected_version}.")
+              sys.exit(1)
+        shell: python
+  test_setup_poetry:
+    name: Test setup-poetry
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Set up Python
+        uses: ./setup-python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Set up Poetry
+        uses: ./setup-poetry
+      - name: Create project
+        run: poetry new test-project
+      - name: Check that the project was created
+        run: |
+          if [ ! -f test-project/pyproject.toml ]; then
+            echo "::error title=Test Failure::The project file does not exist."
+            exit 1
+          fi
+        shell: bash
   test_check_project_version:
     name: Test check-project-version
     runs-on: ubuntu-latest
